//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trabalho_1___C_
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;

    public partial class produto
    {
        public int codigo { get; set; }
        public string descricao { get; set; }
        public Nullable<System.DateTime> datavalidade { get; set; }
        public Nullable<double> preco { get; set; }
        public Nullable<double> taxalucro { get; set; }

        public double calcularPrecoFinal() {

            try {

                if (preco == null || taxalucro == null) {
                    return 0;
                }

                return Convert.ToDouble(this.preco * (100 + this.taxalucro) / 100);
            }
            catch (Exception) {
                throw;
            }

        }

        public int? calcularPrazoValidade() {

            try {

                if (this.datavalidade == null) {
                    return 0;
                }

                return DbFunctions.DiffDays(DateTime.Now, Convert.ToDateTime(this.datavalidade));

            }
            catch (Exception) {
                throw;
            }

        }


    }
}
